version: "2.1"

orbs:
  codecov: codecov/codecov@3.3.0
jobs:
  build:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    docker:
      - image: cimg/openjdk:17.0.9
    resource_class: small
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    docker:
      - image: cimg/openjdk:17.0.9
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run tests
          command:
            ./gradlew test
      - run:
          name: Generate code coverage report
          command:
            ./gradlew jacocoTestReport
      - store_test_results:
          path: core/build/test-results/test
      - store_artifacts:
          path: core/build/test-results/test
      - store_artifacts:
          path: core/build/reports/jacoco/test/html
      - codecov/upload:
          file: core/build/reports/jacoco/test/jacocoTestReport.xml

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build