version: "2.1"

jobs:
  test:
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - checkout
      - run:
          name: Run tests
          command:
            ./gradlew test

workflows:
  version: 2
  workflow:
    jobs:
      - test